import coursesData from "./courses.json";
import moduleData from "./modules.json";
import assignmentData from "./assignments.json";
import usersData from "./users.json";
import enrollmentsData from "./enrollments.json";
const courses = coursesData as any[];
const modules = moduleData as any[];
const assignments = assignmentData as any[];
const users = usersData as any[];
const enrollments = enrollmentsData as any[];
export {  courses, modules, assignments, users, enrollments };